language: ruby
dist: trusty
sudo: required
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - ree
  - rbx-3
before_install:
  - wget https://github.com/mudge/re2/releases/download/$GITHUB_RELEASE/$RE2_PACKAGE
  - sudo dpkg -i $RE2_PACKAGE
  - gem install bundler -v '~> 1.11'
env:
  - GITHUB_RELEASE=v1.2.0 RE2_PACKAGE=libre2-dev_20200409_amd64.deb
  - GITHUB_RELEASE=v1.0.0 RE2_PACKAGE=libre2-dev_20160901_amd64.deb
  - GITHUB_RELEASE=v0.6.0 RE2_PACKAGE=libre2-dev_20130802_amd64.deb
