language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
  - rbx-19mode
before_install:
  - wget https://dl.dropbox.com/u/2175127/libre2-dev_2013.01.14_i386.deb
  - sudo dpkg -i libre2-dev_2013.01.14_i386.deb
